version: '3.5'
services:
  shell:
    image: us.gcr.io/constellation-utils/tools-base-alp:latest
    restart: always
    working_dir: /app
    volumes:
      #Mount application code
      - ./:/app
      #Mount docker socket so that docker can be used on image
      - /var/run/docker.sock:/var/run/docker.sock
      #Mount gCloud configuration
      - ~/.config/gcloud/:/root/.config/gcloud/
 