heb:
  togglr:
    jwt:
      secret:
        id: 101
      session:
        seconds: 600
      tokenheader: X-TOGGLR-TOKEN
    oauth:
      tokenheader: OAUTH-TOKEN
      userIdentification: ${SSOUSERIDFIELD}
      oauthEnabled: ${HEBTOGGLROAUTHENABLED}
logging:
  level:
    com:
      heb: debug
    default: debug
    root: debug
  path: logs
server:
  error:
    whitelabel:
      enabled: false
  port: 8080
  servlet:
    context-path: /togglr-api
  use-forward-headers: true
spring:
  application:
    name: togglr_api
  freemarker:
    enabled: false
  groovy:
    template:
      enabled: false
  jmx:
    enabled: false
  main:
    banner-mode: 'off'
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        clientId: ${SSOCLIENTID}
        clientSecret: ${SSOCLIENTSECRET}
        accessTokenUri: ${SSOACCESSTOKENURI}
        redirectUri: ${SSOREDIRECTURL}
        userAuthorizationUri: ${SSOUSERAUTHORIZATIONURI} # query params client_id and redirect_uri
        clientAuthenticationScheme: form
      resource:
        userInfoUri: ${SSOUSERINFOURI}
        preferTokenInfo: false
# shikha configs
#  security:
#    oauth2:
#      client:
#        clientId: 84aac5770303bea335e3
#        clientSecret: f8562eb2b18b849abfc8f4f2993fc2b743823c33
#        accessTokenUri: https://github.com/login/oauth/access_token
#        userAuthorizationUri: https://github.com/login/oauth/authorize?client_id=84aac5770303bea335e3&redirect_uri=http://localhost:3000/togglr
#        clientAuthenticationScheme: form
#        redirectUri: 'http://localhost:8080/oauth2/authorize/github?redirect_uri=http://localhost:3000/togglr'
#      resource:
#        userInfoUri: https://api.github.com/user
#        preferTokenInfo: false
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
