_meta:
    kms: projects/constellation-prod-242820/locations/global/keyRings/togglr-key-ring/cryptoKeys/togglr-crypto-key
    name: togglr-api-service
    namespace: togglr
    chart: df/df-service
    version: 1.2.0
version: v1
replicaCount: 3
image:
    registry: us.gcr.io/constellation-prod-242820
    name: togglr-api-service
    tag: latest
    pullPolicy: Always
app:
    listenerPort: 8080
    probes:
        initialDelaySeconds: 60
        periodSeconds: 5
        timeoutSeconds: 3
        liveness:
            endpoint: /togglr-api/actuator/health
        readiness:
            endpoint: /togglr-api/actuator/health
cloudsql:
    enabled: true
    useProxy: true
    #  pg or mysql
    type: mysql
    instance: constellation-nonprod:us-central1:gcccsmtogglr
    #  privateIp:
    user_enc: ENC[AES256_GCM,data:y0GtfGLcviGQ8lV6xUWu,iv:cAtfoxGAUzOYgeT624hMTL/ZbhTiBsdLwhpbX38PCLk=,tag:79d7QApAjmiuQBkWpsmBwA==,type:str]
    password_enc: ENC[AES256_GCM,data:dS9clQNvYqfGMBe47Ct0Lw==,iv:KPGu7wE2LLixXdt0SDyCMB2eTex3ySdjRlsn4Cfg/jw=,tag:krK8zfOqna6NnbMI2gEwnA==,type:str]
    database: togglr
    proxyResources:
        limits:
            cpu: 500m
            memory: 500Mi
        requests:
            cpu: 300m
            memory: 300Mi
env:
    staticValues:
        SPRING_DATASOURCE_URL: jdbc:mysql://$(SPRING_DATASOURCE_HOST):$(SPRING_DATASOURCE_PORT)/$(SPRING_DATASOURCE_DATABASE)?verifyServerCertificate=false&useSSL=false&requireSSL=false
    secrets:
        HEB_TOGGLR_CLIENT_APP-ID_enc: ENC[AES256_GCM,data:nQ==,iv:C4jXq2MNMHQJhR6ZaTXY9uB50keM9ZXWyPqO4jrVkYY=,tag:trkOtu8HVymbmkC16eyXYA==,type:str]
        SPRING_SECURITY_USER_PASSWORD_enc: ENC[AES256_GCM,data:7hxypJfuGQ==,iv:7sAcBozi8vNUZ19+LUrgxmnSJJvYvl8s8adj6dQqx9w=,tag:N/otECrrRlezuy+NvBSyaw==,type:str]
        SPRING_SECURITY_USER_NAME_enc: ENC[AES256_GCM,data:rOm7FbaTVD0oztLk,iv:QJgpBebC/BhFkZD+oMLxjxCtu+4XahPzzsuM84rgupI=,tag:+g5KqpwkcCJMDOoTcBaxzQ==,type:str]
    configs:
        HEB_TOGGLR_CLIENT_SERVER-URL: http://localhost:8080/togglr-service/features/active
        SERVER_SERVLET_CONTEXT-PATH: /togglr-api
        SERVER_SERVLET_SESSION_COOKIE_DOMAIN: togglr.df.gcp.heb.com
        SSO_SAML_COOKIE_DOMAIN: togglr.df.gcp.heb.com
        SPRING_PROFILES_ACTIVE: clouddev,mysql
        HEB_TOGGLR_APP-DOMAIN: togglr.df.gcp.heb.com
        HEB_TOGGLR_CACHE-TIME: "15000"
    externalSecrets: null
    externalSecrets:
    -   name: SPRING_DATASOURCE_USERNAME
        secretName: togglr-api-service-cloudsql
        secretKey: CLOUDSQL_USER
    -   name: SPRING_DATASOURCE_PASSWORD
        secretName: togglr-api-service-cloudsql
        secretKey: CLOUDSQL_PASSWORD
    -   name: SPRING_DATASOURCE_HOST
        secretName: togglr-api-service-cloudsql
        secretKey: CLOUDSQL_HOST
    -   name: SPRING_DATASOURCE_PORT
        secretName: togglr-api-service-cloudsql
        secretKey: CLOUDSQL_PORT
    -   name: SPRING_DATASOURCE_DATABASE
        secretName: togglr-api-service-cloudsql
        secretKey: CLOUDSQL_DATABASE
scaler:
    minReplicas: 3
    maxReplicas: 10
    targetMemoryUtilization: 80
    targetCpuUtilization: 80
resources:
    requests:
        cpu: "1"
        memory: 3Gi
    limits:
        cpu: "1"
        memory: 3Gi
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/constellation-prod-242820/locations/global/keyRings/togglr-key-ring/cryptoKeys/togglr-crypto-key
        created_at: '2019-07-24T05:29:49Z'
        enc: CiQAGQnY+7LaZoS/frxManMOYMTqbpVC3ZmkRD0U6lKvk2j3Fx0SSQBSikkEqRiHszqX99jQ6lVQt+8HaT83WLr+Sk8jFKF6X2QQ6xioBPudgsArdzeSenwEcFizWxpXuMHkWAK+6/usNXpF8iYK84k=
    azure_kv: []
    lastmodified: '2019-07-24T05:29:49Z'
    mac: ENC[AES256_GCM,data:TD2pJFnqSLD7W0o/+z0kwoDDZaKAx5NX/Z28INvoKPg39wACYQXEnwFA8IQao13uLXWmWlNK/vGJ8S96cZkCJNV2wO7h+fwckAvToega8IXd784nrOG5sI4jD6tcJMCjOn4WZFvdVzJ0JPi+pY4Lb7fHH+hgvpbgFrgcUsmluJU=,iv:dcnPapuWTaout5BOa6inh2SVAYqVCJgbrgfzLpXWK3Q=,tag:oBYhtK2jxtJR4YFGh2oabw==,type:str]
    pgp: []
    encrypted_suffix: enc
    version: 3.3.1
